[package]
name = "pastey"
version = "0.1.0"
edition = "2018"
description = ""
readme = "README.md"
homepage = "https://github.com/celeo/pastey"
repository = "https://github.com/celeo/pastey"
documentation = "https://docs.rs/pastey"
license = "MIT OR Apache-2.0"
exclude = [
  ".github"
]
keywords = []
categories = []

[dependencies]
axum = "0.1.3"
chrono = "0.4.19"
hyper = "0.14.11"
sqlx = { version = "0.5.5", features = ["runtime-tokio-rustls", "sqlite"] }
tokio = { version = "1.9.0", features = ["full"] }
